# Generated by Django 3.0.6 on 2020-05-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20200527_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweeter',
            old_name='followering',
            new_name='following',
        ),
    ]
